name: Deploy Spring Boot to AWS S3
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: mclass-ins-bucket-1
  AWS_CODE_DEPLOY_APPLICATION: mclass-ins-cd-1
  AWS_CODE_DEPLOY_GROUP: mclass-ins-cd-group-1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    # 1. 기본 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. application.properties 설정
    - uses: actions/checkout@v4
    - run: touch ./src/main/resources/keyproperties/apikeys.properties
    - run: echo "${{ secrets.TRIPANT_APPLICATION }}" > ./src/main/resources/keyproperties/apikeys.properties
    - run: cat ./src/main/resources/keyproperties/apikeys.properties
    
    # 3. gradlew 권한 추가
    # 4. JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven
  
    # 5. Maven build (Test 제외)
    - name: Build with Maven
      run: mvn clean package

    # 6. AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 7. 빌드 결과물을 S3 버킷에 업로드
    - name: Upload to S3
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/cicdtest/$GITHUB_SHA.zip --source .
    # 8. S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
    - name: EC2에 배포
      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=cicdtest/$GITHUB_SHA.zip,bundleType=zip
